version: '3.3'

services:
  ichd_db:
    container_name: ichd_db
    image: postgres:15.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./ichd_db:/var/lib/postgresql/data
  ichd_web:
    container_name: ichd_web
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "python manage.py runserver 0.0.0.0:$PORT"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - ichd_db
    volumes:
      - .:/app/

  ichd_redis:
    container_name: ichd_redis
    image: redis:alpine
  ichd_celery:
    container_name: ichd_celery
    build: .
    command: celery -A backend worker -l info
    volumes:
      - ./:/app/
    restart: always
    env_file:
      - ./.env
    depends_on:
      - ichd_db
      - ichd_redis