# Generated by Django 4.1.5 on 2023-01-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichd', '0003_uploads_create_date_uploads_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='status',
            field=models.CharField(choices=[('progres', 'In progres'), ('finished', 'Finished'), ('error', 'Error')], default='progres', max_length=100),
        ),
    ]
