# Generated by Django 4.1.5 on 2023-01-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ichd', '0004_alter_uploads_create_date_alter_uploads_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='areatable',
            options={'ordering': ['order'], 'verbose_name': 'Area Table', 'verbose_name_plural': 'Area Tables'},
        ),
        migrations.AlterModelOptions(
            name='areatablecriteria',
            options={'ordering': ['criteria__order', 'criteria__name'], 'verbose_name': 'Area Table Criteria', 'verbose_name_plural': 'Area Table Criteria'},
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['order'], 'verbose_name': 'Criteria', 'verbose_name_plural': 'Criteria'},
        ),
        migrations.AlterModelOptions(
            name='datatable',
            options={'verbose_name': 'Data Table', 'verbose_name_plural': 'Data Tables'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='regionsectortable',
            options={'ordering': ['order'], 'verbose_name': 'Region Sector Table', 'verbose_name_plural': 'Region Sector Tables'},
        ),
        migrations.AlterModelOptions(
            name='regionsectortablecriteria',
            options={'ordering': ['criteria__order', 'criteria__name'], 'verbose_name': 'Region Sector Table Criteria', 'verbose_name_plural': 'Region Sector Table Criteria'},
        ),
        migrations.AlterModelOptions(
            name='regiontable',
            options={'ordering': ['order'], 'verbose_name': 'Region Table', 'verbose_name_plural': 'Region Tables'},
        ),
        migrations.AlterModelOptions(
            name='regiontablecriteria',
            options={'ordering': ['criteria__order', 'criteria__name'], 'verbose_name': 'Region Table Criteria', 'verbose_name_plural': 'Region Table Criteria'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['number'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='sectortable',
            options={'ordering': ['order'], 'verbose_name': 'Sector Table', 'verbose_name_plural': 'Sector Tables'},
        ),
        migrations.AlterModelOptions(
            name='sectortablecriteria',
            options={'ordering': ['criteria__order', 'criteria__name'], 'verbose_name': 'Sector Table Criteria', 'verbose_name_plural': 'Sector Table Criteria'},
        ),
        migrations.AlterModelOptions(
            name='uploads',
            options={'ordering': ['-date'], 'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
        migrations.AlterField(
            model_name='criteria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ichd.criteria'),
        ),
    ]
