# Generated by Django 4.1.5 on 2023-01-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ichd', '0006_uploads_message_regiondatatable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiondatatable',
            name='sector',
        ),
    ]
