# Generated by Django 4.1.5 on 2023-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichd', '0007_remove_regiondatatable_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='global_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
