# Generated by Django 4.1.5 on 2023-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichd', '0008_area_global_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('progres', 'In progres'), ('finished', 'Finished'), ('error', 'Error')], default='created', max_length=100),
        ),
    ]
