# Generated by Django 4.1.5 on 2023-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_useroutstandingtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutstandingtoken',
            name='device_id',
            field=models.IntegerField(choices=[[0, 'Desktop'], [1, 'Android'], [2, 'iOS'], [3, 'Mobile WEB']], default=0),
        ),
    ]
