# Generated by Django 4.1.5 on 2023-01-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xlsx')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('progres', 'In progres'), ('finished', 'Finished'), ('error', 'Error')], default='progres', max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Upload Passport',
                'verbose_name_plural': 'Uploads Passport',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passport_indicators.criteria')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_indicators.uploads')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passport_indicators.region')),
            ],
        ),
    ]
