# Generated by Django 4.1.5 on 2023-01-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='region'),
        ),
    ]
